name: first workflow
on: workflow_dispach
jobs:
  first-job:
    runs-on:  
    steps:
      - name: print greeting
        run: echo "Hello world"
      - name: pring goodbye
        run: echo "Bye!"
